# Site settings
locale: en-US
title: "Michael Ramsdail"
name: "Michael Ramsdail"
description: "President & CEO | Strategic Planning • Operations • Community Impact"
url: "https://michael.ramsdail.github.io"
baseurl: ""  # keep empty for user.github.io root sites

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"   # choices: default, air, contrast, dark, dirt, neon, mint, etc.

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5
paginate_path: /page:num/

# Plugins supported by GitHub Pages
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache

# Author profile (appears in sidebar/footers if enabled)
author:
  name: "Michael Ramsdail"
  avatar: "/assets/images/headshot.jpg"
  bio: "Dynamic executive with 20+ years leading strategy, operations, and community-focused growth across nonprofits, education, hospitality, and senior living."
  location: "Aurora, CO"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/michael-ramsdail-1467ba138/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:michael.ramsdail@gmail.com"

# Defaults for pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      toc: false
      classes: wide

# Navigation (uses _data/navigation.yml)
collections: {}

# SEO & social
social:
  type: Person
  name: "Michael Ramsdail"
  links:
    - "https://www.linkedin.com/in/michael-ramsdail-1467ba138/"
    - "mailto:michael.ramsdail@gmail.com"

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Google Analytics (optional)
# analytics:
#   provider: "google-gtag"
#   google:
#     tracking_id: "G-XXXXXXXXXX"
